---
kind: pipeline
type: docker
name: default-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    pull: always
    image: rancher/dapper:v0.4.1
    environment:
      CROSS: "true"
    commands:
      - dapper ci
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - push
        - pull_request
        - tag

  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-amd64.txt
      checksum_flatten: true
      files:
        - "dist/artifacts/*"
    when:
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: docker-publish-head
    image: plugins/docker
    settings:
      build_args:
        - ARCH=amd64
      custom_dns: 1.1.1.1
      dockerfile: package/Dockerfile
      tag: latest
      password:
        from_secret: docker_password
      repo: cnrancher/webhook-receiver
      username:
        from_secret: docker_username
    when:
      ref:
        include:
          - "refs/heads/master"
      event:
        - push

  - name: install-buildx-support
    image: tonistiigi/binfmt
    privileged: true
    entrypoint:
      - /usr/bin/binfmt
    command:
      - --install
      - all
    when:
      branch:
        - pandaria
      event:
        - tag

  - name: docker-publish
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      platforms: linux/amd64,linux/arm64/v8
      custom_dns: 1.1.1.1
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: cnrancher/webhook-receiver
      tag: "${DRONE_TAG}"
      username:
        from_secret: docker_username
    when:
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

node:
  instance: agent-amd64

trigger:
  event:
    exclude:
      - promote
